POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwYjE1NGI2ZjM4YjFkMWViYzRiNDdhMyIsImlhdCI6MTYyMjI5Nzk0MH0.jT3IihlCUSI79hhwv73AUx4sIj1cWiSfK_OzrKOA2tc

{
  "title": "Guccin wellingtonblogi",
  "author": "Kusti",
  "url": "http://beefwellingtons.fi",
  "likes": "1917",
  "userId": "60b154b6f38b1d1ebc4b47a3"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "Guccin wellingtonblogi",
  "author": "Kusti",
  "url": "http://beefwellingtons.fi",
  "likes": "1917"
}

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "blogs": [],
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
    "username": "root",
    "password": "salainen"
}

###
DELETE http://localhost:3003/api/blogs/60b256e24b25205a6cafa596 HTTP/1.1
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwYjE1NGI2ZjM4YjFkMWViYzRiNDdhMyIsImlhdCI6MTYyMjI5Nzk0MH0.jT3IihlCUSI79hhwv73AUx4sIj1cWiSfK_OzrKOA2tc

###
PUT http://localhost:3003/api/blogs/60b256e24b25205a6cafa596 HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwYjE1NGI2ZjM4YjFkMWViYzRiNDdhMyIsImlhdCI6MTYyMjI5Nzk0MH0.jT3IihlCUSI79hhwv73AUx4sIj1cWiSfK_OzrKOA2tc

{
  "title": "Guccin tacoblogi",
  "author": "Kusti",
  "url": "http://tacos.gov",
  "likes": "1917",
  "user": "60b154b6f38b1d1ebc4b47a3"
}

###
PUT http://localhost:3003/api/users/60b154b6f38b1d1ebc4b47a3 HTTP/1.1
content-type: application/json

{
  "blogs": [
    "60b15c473e58aa1134cc0a73"
  ],
  "username": "root",
  "name": "Superuser",
  "password": "salainen"
}